version: '3.8'

services:
  test_users_api:
    container_name: test_users_api
    env_file:
      - .env
    environment:
      REDIS_HOST: 'test_app_redis'
      REDIS_DB: 1
      DB_HOST: 'test_app_db'
      DB_NAME: ${TEST_DB_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        echo 'Launching tests...' &&
        alembic upgrade head
        pytest
      "
    networks:
      - prod_network
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      test_app_db:
        condition: service_healthy
      test_app_redis:
        condition: service_healthy


  test_app_db:
    container_name: test_app_db
    image: postgres:15.1-alpine
    volumes:
      - psql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - '5432:5432'
    networks:
      - prod_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${TEST_DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 10

  test_app_redis:
    container_name: test_app_redis
    image: redis:latest
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - prod_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  prod_network:
    name: prod_network
    driver: bridge

volumes:
  psql:
