# Auth
LOGIN = '/login'
LOGOUT = '/logout'

# User
USER_PREFIX = '/users'

USER_LIST = ''
USER_DETAIL = USER_UPDATE = '/current'

USERS_LIST_FULL = USER_PREFIX + USER_LIST
USER_DETAIL_FULL = USER_PREFIX + USER_DETAIL
USER_UPDATE_FULL = USER_PREFIX + USER_UPDATE

# Admin
PRIVATE_PREFIX = '/private'

PRIVATE_USERS_LIST = PRIVATE_USER_CREATE = '/users'
PRIVATE_USER_DETAIL = PRIVATE_USER_UPDATE = PRIVATE_USER_DELETE = '/users/{pk}'

PRIVATE_USERS_LIST_FULL = PRIVATE_PREFIX + PRIVATE_USERS_LIST
PRIVATE_USER_CREATE_FULL = PRIVATE_PREFIX + PRIVATE_USER_CREATE
PRIVATE_USER_DETAIL_FULL = PRIVATE_PREFIX + PRIVATE_USER_DETAIL
PRIVATE_USER_UPDATE_FULL = PRIVATE_PREFIX + PRIVATE_USER_UPDATE
PRIVATE_USER_DELETE_FULL = PRIVATE_PREFIX + PRIVATE_USER_DELETE

# Messages
MSG_LOGGED_OUT = 'Logged out successfully.'
